# Generated by Django 4.2.15 on 2024-08-23 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_date_task_day_task_time_alter_task_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_completed',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='day',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
    ]
